### ISSUE TITLE
Adapt time position in ambient mode

### ISSUE THREAD

**Issue by lucasdesvages** [CorvetteCole/PixelWatchFace#25]
When only the time is displayed in ambiant mode, it should be centered on the screen.

**Comment by CorvetteCole** [comment]
When you mean only the time, can you clarify the cases a bit?

For example, if battery percent is shown in ambient should the time be centered still? 


Thanks for making this issue

**Comment by davwheat** [comment]
In my opinion, the time should always be exactly centred.

**Comment by CorvetteCole** [comment]
@davwheat the only reason it isn't is because I feel like it cramps up the screen when the battery percentage is enabled. If that isn't as much a problem for people I think what I might do is center the time always, but move it up when displaying an at a glance style next event widget underneath the time (future planned feature). I could provide an option for this but there are so many settings already I'm trying to simplify that. Not sure, will need some more opinions and testing

**Comment by lucasdesvages** [comment]
![IMG_20200305_194953](https://user-images.githubusercontent.com/15828799/76015428-7df22b80-5f1b-11ea-9b6f-adb47af14a4f.jpg)
This picture that illustrates my point I think. It is ambient mode. And in my setup, logo, battery, date/weather in ambient mode are off

**Comment by CorvetteCole** [comment]
I see what you mean. I'm a bit worried about having a different position of the time in ambient vs not (since the info bar is below it in live mode). Would you think the time should be centered then as well and just pin the infobar under it?


I'm thinking if the user chooses to not show infobar in ambient, the time will center itself on the watch, otherwise it will behave as it already does

**Comment by lucasdesvages** [comment]
> I see what you mean. I'm a bit worried about having a different position of the time in ambient vs not (since the info bar is below it in live mode). Would you think the time should be centered then as well and just pin the infobar under it?

I agree. It has a better effect when going from a mode the other. The time should be at the same position in both modes.

> I'm thinking if the user chooses to not show infobar in ambient, the time will center itself on the watch, otherwise it will behave as it already does

I am okay with that too.

By the way, it is awesome to ask for our opinion. You are making a great work on this app!!

**Comment by davwheat** [comment]
With more and more options, it might be worthwhile separating them into
separate categories in the app.

**Comment by CorvetteCole** [comment]
right, sounds good then. Thanks for the clarification. Love hearing from the users to make sure I can make this the best app for us all to use :)

**Comment by CorvetteCole** [comment]
@davwheat I'm going to completely redesign the phone app shortly. The rough idea I have is give the user 3 preset "config" of settings that they can pick through with an easy preview of all 3 initially. Then they can customize that however they choose with all the existing settings (sorted in to categories)

**Comment by davwheat** [comment]
That sounds fab! Looking forward to it :)

**Comment by CorvetteCole** [comment]
https://github.com/CorvetteCole/PixelWatchFace/commit/2a01c416afb1d9ef7d0a03000eefe0f5d66ab2d4 implements this, although the position of the time will change between ambient and not. I will be testing this in beta at some point before a wider release to listen for complaints. Not rolling out to the Play Store yet.

**Comment by davwheat** [comment]
Can't wait to get the beta version (if you're rolling that to the play
store).
